// src/utils/imageMap.ts
const imageMap: { [key: string]: any } = {
    'banner_acompañamientos.jpg': require('../../assets/images/banner_acompañamientos.jpg'),
    'banner_bebidas.jpg': require('../../assets/images/banner_bebidas.jpg'),
    'banner_entrada.jpg': require('../../assets/images/banner_entrada.jpg'),
    'banner_menu_niños.png': require('../../assets/images/banner_menu_niños.png'),
    'banner_postres.jpg': require('../../assets/images/banner_postres.jpg'),
    'banner_principal.jpg': require('../../assets/images/banner_principal.jpg'),
    'agua_mineral.jpg': require('../../assets/images/platillos/agua_mineral.jpg'),
    'brownie.jpg': require('../../assets/images/platillos/brownie.jpg'),
    'ensalada_cesar.jpg': require('../../assets/images/platillos/ensalada_cesar.jpg'),
    'ensalada_mixta.jpg': require('../../assets/images/platillos/ensalada_mixta.jpg'),
    'espagueti_carbonara.jpg': require('../../assets/images/platillos/espagueti_carbonara.jpg'),
    'hamburguesa.jpg': require('../../assets/images/platillos/hamburguesa.jpg'),
    'helado_fresa.jpg': require('../../assets/images/platillos/helado_fresa.jpg'),
    'limonada.jpg': require('../../assets/images/platillos/limonada.jpg'),
    'nachos.jpg': require('../../assets/images/platillos/nachos.jpg'),
    'panini.jpg': require('../../assets/images/platillos/panini.jpg'),
    'pasta_alfredo.jpg': require('../../assets/images/platillos/pasta_alfredo.jpg'),
    'pastel_chocolate.jpg': require('../../assets/images/platillos/pastel_chocolate.jpg'),
    'pizza_margarita.jpg': require('../../assets/images/platillos/pizza_margarita.jpg'),
    'pizza_pepperoni.jpg': require('../../assets/images/platillos/pizza_pepperoni.jpg'),
    'pizza_vegetariana.jpg': require('../../assets/images/platillos/pizza_vegetariana.jpg'),
    'sandwich_club.jpg': require('../../assets/images/platillos/sandwich_club.jpg'),
    'soda.jpg': require('../../assets/images/platillos/soda.jpg'),
    'sopa_tomate.jpg': require('../../assets/images/platillos/sopa_tomate.jpg'),
    'tarta_manzana.jpg': require('../../assets/images/platillos/tarta_manzana.jpg'),
    'te_helado.jpg': require('../../assets/images/platillos/te_helado.jpg'),
  };
  
  export default imageMap;